name: vocabulary-ai
services:
  redis:
    image: redis:latest
    container_name: vocabulary-ai-redis
    restart: unless-stopped
    ports:
      - 6388:6379
    volumes:
      - vocabulary_ai_redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  postgres:
    image: postgres:latest
    container_name: vocabulary-ai-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vocabulary
    ports:
      - 5433:5432
    volumes:
      - vocabulary_ai_postgres_data:/var/lib/postgresql/data

volumes:
  vocabulary_ai_postgres_data:
    driver: local
  vocabulary_ai_redis_data:
    driver: local
